import { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'es' | 'en';

// ---------------------------------------------------------------------------
// Spanish dictionary (source of truth for the shape)
// ---------------------------------------------------------------------------
const es = {
  meta: {
    title: 'Sistema de Predicción de Remisión a Psiquiatría',
  },

  nav: {
    home: 'Inicio',
    prediction: 'Predicción',
    results: 'Resultados',
    dashboard: 'Dashboard',
    legal: 'Legal',
  },

  common: {
    select: 'Seleccionar',
    years: 'años',
    cases: 'casos',
    notSpecified: 'No especificado',
  },

  // Enum VALUES used by the prediction logic are NEVER translated.
  // This map only translates the visible label for each stored value.
  values: {
    'FEMENINO': 'Femenino',
    'MASCULINO': 'Masculino',
    'NO': 'No',
    'SI': 'Sí',
    'SOLTERO(A)': 'Soltero(a)',
    'UNION LIBRE': 'Unión Libre',
    'CASADO(A)': 'Casado(a)',
    'DIVORCIADO(A)': 'Divorciado(a)',
    'VIUDO(A)': 'Viudo(a)',
    'PREESCOLAR': 'Preescolar',
    'BASICA PRIMARIA': 'Básica Primaria',
    'BASICA SECUNDARIA': 'Básica Secundaria',
    'MEDIA TECNICA': 'Media Técnica',
    'TECNICA O TECNOLOGICA': 'Técnica o Tecnológica',
    'PROFESIONAL': 'Profesional',
    'ESPECIALIZACION': 'Especialización',
    'MAESTRIA': 'Maestría',
    'INTOXICACIONES': 'Intoxicaciones',
    'ARMA CORTOPUNZANTE': 'Arma Cortopunzante',
    'AHORCAMIENTO': 'Ahorcamiento',
    'LANZAMIENTO AL VACIO': 'Lanzamiento al Vacío',
    'LANZAMIENTO A VEHICULO': 'Lanzamiento a Vehículo',
    'ARMA DE FUEGO': 'Arma de Fuego',
    'INMOLACION': 'Inmolación',
    'OTROS': 'Otros',
  } as Record<string, string>,

  // Internal risk-level values ('Alto' | 'Moderado' | 'Bajo' | 'Específico')
  // stay in Spanish for the logic; only the visible label is translated.
  riskLevels: {
    'Alto': 'Alto',
    'Moderado': 'Moderado',
    'Bajo': 'Bajo',
    'Específico': 'Específico',
  } as Record<string, string>,

  // Full labels for the 23 clinical variables (form + variables grid)
  fields: {
    edad: 'Edad de la Víctima',
    sexo: 'Sexo',
    estrato: 'Estrato Socioeconómico',
    gestante: 'Gestante',
    estadoCivil: 'Estado Civil',
    escolaridad: 'Escolaridad',
    conflictoPareja: 'Conflicto con Pareja o Ex Pareja',
    problemasFamiliares: 'Problemas Familiares',
    problemasLaborales: 'Problemas Laborales',
    problemasJuridicos: 'Problemas Jurídicos',
    problemasEconomicos: 'Problemas Económicos',
    muerteFamiliar: 'Muerte de un Familiar',
    antecedenteViolencia: 'Antecedente de Violencia o Abuso',
    trastornoDepresivo: 'Trastorno Depresivo',
    trastornoBipolar: 'Trastorno Bipolar',
    trastornoPersonalidad: 'Trastorno de Personalidad',
    esquizofrenia: 'Esquizofrenia',
    ideacionSuicida: 'Ideación Suicida Persistente',
    antecedentesFamiliares: 'Antecedentes Familiares de Conducta Suicida',
    consumoSPA: 'Consumo de SPA (Sustancias Psicoactivas)',
    enfermedadCronica: 'Enfermedad Crónica Dolorosa o Discapacitante',
    metodoSuicidio: 'Método de Suicidio',
    intentosPrevios: 'Número de Intentos Previos',
  } as Record<string, string>,

  // Short labels reused in review panels / case summary
  shortLabels: {
    edad: 'Edad',
    sexo: 'Sexo',
    estrato: 'Estrato',
    estadoCivil: 'Estado Civil',
    escolaridad: 'Escolaridad',
    metodo: 'Método',
    intentosPrevios: 'Intentos Previos',
    trastornoDepresivo: 'Trastorno Depresivo',
    ideacionSuicida: 'Ideación Suicida',
    consumoSPA: 'Consumo SPA',
    problemasFamiliares: 'Problemas Familiares',
    conflictoPareja: 'Conflicto Pareja',
    antecedenteViolencia: 'Antecedentes Violencia',
    antecedentesFamiliares: 'Antecedentes familiares',
    problemasLaborales: 'Problemas laborales',
  },

  landing: {
    title: 'Sistema de Predicción de Remisión a Psiquiatría',
    subtitle: 'Modelo Stacking Classifier con 96% de precisión (F1-Score) para apoyo en decisiones clínicas',
    heroText: 'Sistema avanzado que utiliza K-Means con 3 clústeres optimizados para segmentar perfiles de riesgo y proporcionar predicciones precisas basadas en 23 variables del dataset real.',
    startButton: 'Iniciar Evaluación',
    metricAccuracy: 'Precisión del Modelo',
    metricAccuracySub: '(F1-Score)',
    metricRecall: 'Recall del Sistema',
    metricRecallSub: 'Detección completa',
    metricClusters: 'Clústeres K-Means',
    metricClustersSub: 'Perfiles optimizados',
    metricVariables: 'Variables Analizadas',
    metricVariablesSub: 'Dataset completo',
    howItWorks: 'Cómo Funciona',
    step1Title: 'Captura de Datos',
    step1Desc: 'Recolección de 23 variables del dataset real incluyendo demografía, factores de riesgo y condiciones clínicas.',
    step2Title: 'Análisis IA',
    step2Desc: 'Procesamiento mediante Stacking Classifier entrenado con datos reales y segmentación K-Means optimizada.',
    step3Title: 'Resultados',
    step3Desc: 'Probabilidad de remisión calculada con recomendaciones específicas basadas en el perfil de riesgo identificado.',
    riskProfilesTitle: 'Perfiles de Riesgo K-Means',
    riskProfilesIntro: 'Nuestro sistema utiliza clustering K-Means con 3 clústeres optimizados, superando metodologías como DBSCAN en interpretabilidad y acción clínica:',
    cluster1Title: 'Clúster 1: Alto Riesgo',
    cluster1Desc: 'Jóvenes con múltiples factores de riesgo, métodos de alta letalidad y bajo apoyo familiar.',
    cluster2Title: 'Clúster 2: Riesgo Moderado',
    cluster2Desc: 'Adultos con comorbilidades médicas y depresión mayor, métodos de baja-media letalidad.',
    cluster3Title: 'Clúster 3: Riesgo Específico',
    cluster3Desc: 'Adultos mayores con aislamiento social y pérdidas recientes, planificación detallada.',
  },

  form: {
    step1Title: 'Información Demográfica',
    step2Title: 'Factores Sociales y Relacionales',
    step3Title: 'Condiciones de Salud Mental',
    step4Title: 'Método e Historial de Intentos',
    step5Title: 'Revisión Final',
    agePlaceholder: '0-120 años',
    attemptsPlaceholder: '0-20',
    stepOf: (current: number, total: number) => `Paso ${current} de ${total}`,
    completed: (pct: number) => `${pct}% completado`,
    backToHome: 'Volver al Inicio',
    previous: 'Anterior',
    next: 'Siguiente',
    generate: 'Generar Predicción',
    reviewDemographics: 'Panel Demografía',
    reviewClinical: 'Panel Condiciones Clínicas',
    reviewRiskFactors: 'Panel Factores de Riesgo',
    modelInfoTitle: '⚠️ Información del Modelo',
    modelInfoText: 'Este análisis utiliza un Stacking Classifier entrenado con 23 variables del dataset real, logrando un F1-Score del 96% y un Recall del 100%. Los resultados son una herramienta de apoyo para decisiones clínicas y requieren supervisión profesional.',
  },

  results: {
    title: 'Resultados de Predicción',
    export: 'Exportar',
    share: 'Compartir',
    probabilityTitle: 'Probabilidad de Remisión',
    riskLevelLabel: 'Nivel de Riesgo:',
    recommendationTitle: 'Recomendación Clínica',
    recommendationHigh: 'Remisión inmediata a psiquiatría recomendada. Considere hospitalización y seguimiento intensivo.',
    recommendationModerate: 'Remisión a psiquiatría dentro de 24-48 horas. Establecer plan de seguridad y seguimiento.',
    recommendationLow: 'Evaluación psicológica ambulatoria recomendada. Monitoreo continuo de factores de riesgo.',
    modelMetricsTitle: 'Métricas del Modelo',
    modelMetricsText: 'Stacking Classifier entrenado con dataset real de 487 casos. Combina múltiples algoritmos para maximizar precisión predictiva.',
    f1Score: 'F1-Score',
    recall: 'Recall',
    riskFactorsTitle: 'Factores de Riesgo Identificados',
    noRiskFactors: 'No se identificaron factores de riesgo significativos',
    factorYoungAge: 'Edad joven (< 25 años)',
    factorPreviousAttempts: 'Intentos previos',
    factorDepressive: 'Trastorno depresivo presente',
    factorSuicidalIdeation: 'Ideación suicida persistente',
    factorSubstanceUse: 'Consumo de sustancias',
    factorFamilyHistory: 'Antecedentes familiares',
    factorFamilyProblems: 'Problemas familiares',
    factorPartnerConflict: 'Conflicto pareja',
    factorViolenceHistory: 'Antecedentes violencia',
    caseSummaryTitle: 'Resumen del Caso',
    demographics: 'Demografía',
    clinical: 'Clínico',
    riskFactors: 'Factores de Riesgo',
    variablesTitle: 'Variables del Modelo (23 factores)',
    newEvaluation: 'Nueva Evaluación',
    viewDashboard: 'Ver Dashboard',
    disclaimerTitle: '⚠️ Disclaimer Médico',
    disclaimerText: 'Este sistema es una herramienta de apoyo para decisiones clínicas y NO reemplaza el juicio médico profesional. Los resultados deben interpretarse por personal de salud calificado. Siempre considere la evaluación clínica integral del paciente y las circunstancias específicas del caso. En situaciones de emergencia, contacte inmediatamente a los servicios de salud mental de urgencias.',
  },

  dashboard: {
    title: 'Dashboard de Análisis',
    subtitle: 'Estadísticas y perfiles de riesgo basados en K-Means',
    period1m: '1 mes',
    period3m: '3 meses',
    period6m: '6 meses',
    period1y: '1 año',
    regionAll: 'Todas',
    regionUrban: 'Urbana',
    regionRural: 'Rural',
    regionSuburban: 'Suburbana',
    totalCases: 'Total Casos',
    totalCasesSub: 'Suma de los 3 clústeres',
    avgReferral: 'Remisión Promedio',
    avgReferralSub: 'Promedio entre clústeres',
    kmeansClusters: 'Clústeres K-Means',
    kmeansClustersSub: 'Perfiles optimizados',
    aiAccuracy: 'Precisión IA',
    aiAccuracySub: 'F1-Score Stacking',
    tabProfiles: 'Perfiles de Riesgo',
    tabTrends: 'Tendencias',
    tabDemographics: 'Demografía',
    tabGeography: 'Geografía',
    clusterLabel: 'Clúster',
    riskLabel: 'Riesgo',
    casesLabel: 'Casos',
    avgAge: 'Edad promedio',
    referralRate: 'Tasa remisión',
    avgStay: 'Días estancia',
    characteristics: 'Características:',
    cluster1Title: 'Jóvenes con Múltiples Factores de Riesgo',
    cluster1Chars: [
      'Consumo de alcohol/drogas',
      'Desempleo frecuente',
      'Métodos de alta letalidad',
      'Intentos previos múltiples',
      'Bajo apoyo familiar',
      'Problemas legales',
    ],
    cluster2Title: 'Adultos con Comorbilidades Médicas',
    cluster2Chars: [
      'Enfermedades crónicas',
      'Depresión mayor',
      'Dolor crónico persistente',
      'Limitaciones funcionales',
      'Métodos baja-media letalidad',
      'Aislamiento social moderado',
    ],
    cluster3Title: 'Adultos Mayores con Aislamiento Social',
    cluster3Chars: [
      'Pérdidas recientes significativas',
      'Aislamiento social severo',
      'Deterioro cognitivo incipiente',
      'Métodos altamente letales',
      'Planificación detallada',
      'Pérdida de autonomía',
    ],
    trendsChartTitle: 'Evolución Casos vs Remisiones (6 meses)',
    trendsChartPlaceholder: 'Gráfico de tendencias temporales',
    trendsChartNote: 'Tendencia creciente en detección temprana (+12% últimos 3 meses)',
    triggersTitle: 'Factores Desencadenantes Más Comunes',
    triggerFamily: 'Problemas familiares',
    triggerDepressive: 'Trastorno depresivo',
    triggerSubstance: 'Consumo de SPA',
    triggerEconomic: 'Problemas económicos',
    ageDistTitle: 'Distribución por Edad',
    ageDistPlaceholder: 'Gráfico circular de grupos etarios',
    ageGroup1: '18-25 años: 40.5%',
    ageGroup2: '26-45 años: 33.7%',
    ageGroup3: '45+ años: 25.8%',
    methodsByGenderTitle: 'Métodos por Género',
    femaleLabel: 'Femenino (62%)',
    maleLabel: 'Masculino (38%)',
    methodPoisoning: 'Intoxicaciones',
    methodSharpWeapon: 'Arma cortopunzante',
    methodOther: 'Otros métodos',
    methodHanging: 'Ahorcamiento',
    methodFirearm: 'Arma de fuego',
    methodJumping: 'Lanzamiento al vacío',
    casesByRegionTitle: 'Casos por Región',
    regionCentral: 'Región Central',
    regionNorth: 'Región Norte',
    regionSouth: 'Región Sur',
    regionEast: 'Región Oriental',
    regionWest: 'Región Occidental',
    geoCorrelationTitle: 'Correlación Ubicación-Riesgo',
    geoCorrelationPlaceholder: 'Mapa de correlación geográfica',
    geoCorrelationNote: 'Mayor concentración de casos en zonas urbanas centrales',
  },

  legal: {
    title: 'Información Legal y Soporte',
    subtitle: 'Términos de uso, políticas de privacidad y información importante sobre el sistema',
    sectionDisclaimer: 'Disclaimer Médico',
    sectionTerms: 'Términos de Uso',
    sectionPrivacy: 'Política de Privacidad',
    sectionModel: 'Información del Modelo',
    sectionContact: 'Contacto y Soporte',

    // Disclaimer
    importantTitle: '⚠️ IMPORTANTE - LEER ANTES DE USAR',
    importantText: 'Este sistema es ÚNICAMENTE una herramienta de apoyo para decisiones clínicas. NO constituye un diagnóstico médico ni reemplaza la evaluación profesional.',
    limitationsTitle: 'Limitaciones del Sistema',
    limitation1: 'Los resultados son probabilísticos y deben interpretarse por personal médico calificado',
    limitation2: 'No considera factores clínicos específicos no incluidos en las 23 variables del modelo',
    limitation3: 'Requiere supervisión y validación por parte de profesionales en salud mental',
    limitation4: 'No debe utilizarse como único criterio para tomar decisiones clínicas',
    responsibilityTitle: 'Responsabilidad Profesional',
    responsibilityText: 'El médico tratante mantiene la responsabilidad completa sobre el diagnóstico, tratamiento y seguimiento del paciente. Este sistema proporciona información complementaria que debe ser evaluada en el contexto clínico integral del caso.',
    emergencyTitle: 'Situaciones de Emergencia',
    emergencyText: 'En casos de riesgo inminente o emergencias psiquiátricas, contacte inmediatamente:',
    emergencyLine1: '• Línea de Crisis: 123 (24 horas)',
    emergencyLine2: '• Servicios de Urgencias del hospital más cercano',
    emergencyLine3: '• No dependa exclusivamente de este sistema para decisiones urgentes',

    // Terms
    conditionsTitle: 'Condiciones de Uso',
    condition1: 'Este sistema está destinado exclusivamente para profesionales de la salud',
    condition2: 'Se requiere licencia médica vigente para el uso clínico de los resultados',
    condition3: 'Prohibido el uso para propósitos no médicos o de investigación sin autorización',
    condition4: 'Los usuarios son responsables de mantener la confidencialidad de los datos del paciente',
    condition5: 'Se debe cumplir con todas las normativas locales e internacionales de salud',
    liabilityTitle: 'Limitaciones de Responsabilidad',
    liabilityText: 'El sistema se proporciona "tal como está" sin garantías de ningún tipo. No nos hacemos responsables por decisiones clínicas tomadas basándose únicamente en los resultados del sistema.',
    appropriateUseTitle: 'Uso Apropiado',
    appropriateUse1: 'Utilice como herramienta de apoyo complementaria',
    appropriateUse2: 'Combine siempre con evaluación clínica integral',
    appropriateUse3: 'Documente el uso del sistema en la historia clínica',
    appropriateUse4: 'Mantenga registros de las evaluaciones realizadas',
    updatesTitle: 'Actualizaciones y Modificaciones',
    updatesText: 'Nos reservamos el derecho de actualizar estos términos y las funcionalidades del sistema. Los usuarios serán notificados de cambios significativos.',

    // Privacy
    dataHandlingTitle: 'Manejo de Datos del Paciente',
    privacyCommitmentLabel: 'Compromiso de Privacidad:',
    privacyCommitmentText: ' Todos los datos ingresados son procesados de forma local y no se almacenan en servidores externos sin consentimiento explícito.',
    dataCollectionTitle: 'Recolección de Información',
    dataCollection1: 'Solo recolectamos las 23 variables necesarias para el modelo predictivo',
    dataCollection2: 'No almacenamos información personal identificable sin autorización',
    dataCollection3: 'Los datos se procesan de forma anónima y agregada para estadísticas',
    dataCollection4: 'Cumplimos con estándares HIPAA y normativas locales de protección de datos',
    userRightsTitle: 'Derechos del Usuario',
    userRight1: 'Derecho a conocer qué datos se procesan',
    userRight2: 'Derecho a solicitar eliminación de datos almacenados',
    userRight3: 'Derecho a rectificación de información incorrecta',
    userRight4: 'Derecho a portabilidad de los datos',
    dataSecurityTitle: 'Seguridad de Datos',
    dataSecurityIntro: 'Implementamos medidas técnicas y organizacionales para proteger la información:',
    security1: 'Encriptación de datos en tránsito y reposo',
    security2: 'Acceso controlado y autenticación de usuarios',
    security3: 'Auditorías regulares de seguridad',
    security4: 'Respaldo y recuperación de datos seguros',
    sharingTitle: 'Compartir Información',
    sharingText: 'No compartimos datos personales de pacientes con terceros sin consentimiento explícito, excepto cuando sea requerido por ley o para fines de investigación médica aprobados por comités de ética.',

    // Model
    methodologyTitle: 'Metodología Stacking Classifier',
    advancedTechniqueLabel: 'Técnica Avanzada:',
    advancedTechniqueText: ' Combina múltiples algoritmos de machine learning para maximizar la precisión predictiva y minimizar errores de clasificación.',
    datasetTitle: 'Dataset y Variables',
    trainingDataTitle: 'Datos de Entrenamiento',
    trainingData1: '• 487 casos reales validados',
    trainingData2: '• 3 clústeres K-Means optimizados',
    trainingData3: '• Validación cruzada 10-fold',
    trainingData4: '• Balanceo de clases aplicado',
    modelVariablesTitle: 'Variables del Modelo',
    modelVariables1: '• 6 variables demográficas',
    modelVariables2: '• 7 factores sociales/relacionales',
    modelVariables3: '• 8 condiciones de salud mental',
    modelVariables4: '• 2 variables de método/historial',
    performanceTitle: 'Métricas de Rendimiento',
    precisionLabel: 'Precisión',
    modelLimitationsTitle: 'Limitaciones del Modelo',
    modelLimitation1: 'Entrenado con población específica (puede requerir calibración para otras poblaciones)',
    modelLimitation2: 'No incluye variables de neuroimagen o biomarcadores',
    modelLimitation3: 'Requiere actualización periódica con nuevos datos',
    modelLimitation4: 'Sensible a calidad y completitud de los datos de entrada',
    clinicalValidationTitle: 'Validación Clínica',
    clinicalValidationText: 'El modelo ha sido validado en estudios retrospectivos y requiere validación prospectiva continua. Se recomienda monitoreo regular del rendimiento en condiciones clínicas reales.',

    // Contact
    contactInfoTitle: 'Información de Contacto',
    techSupportTitle: 'Soporte Técnico',
    emailLabel: 'Email:',
    phoneLabel: 'Teléfono:',
    scheduleLabel: 'Horario:',
    responseLabel: 'Respuesta:',
    techSchedule: 'Lunes a Viernes, 8:00 AM - 6:00 PM',
    techResponse: '24-48 horas',
    clinicalInquiriesTitle: 'Consultas Clínicas',
    clinicalSchedule: '24/7 para emergencias',
    clinicalResponse: 'Inmediata para urgencias',
    reportProblemsTitle: 'Reportar Problemas',
    reportProblemsIntro: 'Para reportar problemas técnicos o errores del sistema:',
    report1: 'Describa el problema con detalle',
    report2: 'Incluya pasos para reproducir el error',
    report3: 'Adjunte capturas de pantalla si es posible',
    report4: 'Proporcione información del navegador/dispositivo',
    trainingTitle: 'Capacitación y Entrenamiento',
    trainingText: 'Ofrecemos sesiones de capacitación para equipos médicos sobre el uso apropiado del sistema y interpretación de resultados.',
    training1: 'Workshops presenciales y virtuales',
    training2: 'Materiales de capacitación descargables',
    training3: 'Certificación en uso del sistema',
    training4: 'Consultoría en implementación',
    researchTitle: 'Investigación y Colaboraciones',
    researchIntro: 'Para propuestas de investigación o colaboraciones académicas:',
    researchNote: 'Estamos interesados en colaboraciones para mejorar el modelo y expandir su aplicación a diferentes poblaciones.',
    systemUpdatesTitle: 'Actualizaciones del Sistema',
    systemUpdatesText: 'Para recibir notificaciones sobre actualizaciones, nuevas funcionalidades y boletines de investigación, suscríbase a nuestra lista de correos en:',

    // Footer
    footerTitle: 'Sistema de Predicción de Remisión a Psiquiatría',
    footerModel: 'Modelo Stacking Classifier - F1-Score 96% - Versión 1.0',
    footerCopyright: '© 2025 - Todos los derechos reservados - Uso exclusivo para profesionales de la salud',
  },
};

// ---------------------------------------------------------------------------
// English dictionary — careful medical/legal translation
// ---------------------------------------------------------------------------
const en: typeof es = {
  meta: {
    title: 'Psychiatric Referral Prediction System',
  },

  nav: {
    home: 'Home',
    prediction: 'Prediction',
    results: 'Results',
    dashboard: 'Dashboard',
    legal: 'Legal',
  },

  common: {
    select: 'Select',
    years: 'years',
    cases: 'cases',
    notSpecified: 'Not specified',
  },

  values: {
    'FEMENINO': 'Female',
    'MASCULINO': 'Male',
    'NO': 'No',
    'SI': 'Yes',
    'SOLTERO(A)': 'Single',
    'UNION LIBRE': 'Common-Law Union',
    'CASADO(A)': 'Married',
    'DIVORCIADO(A)': 'Divorced',
    'VIUDO(A)': 'Widowed',
    'PREESCOLAR': 'Preschool',
    'BASICA PRIMARIA': 'Primary Education',
    'BASICA SECUNDARIA': 'Lower Secondary Education',
    'MEDIA TECNICA': 'Technical Upper Secondary',
    'TECNICA O TECNOLOGICA': 'Technical or Technological Degree',
    'PROFESIONAL': "Bachelor's Degree",
    'ESPECIALIZACION': 'Graduate Specialization',
    'MAESTRIA': "Master's Degree",
    'INTOXICACIONES': 'Poisoning',
    'ARMA CORTOPUNZANTE': 'Sharp Weapon',
    'AHORCAMIENTO': 'Hanging',
    'LANZAMIENTO AL VACIO': 'Jumping from a Height',
    'LANZAMIENTO A VEHICULO': 'Jumping in Front of a Vehicle',
    'ARMA DE FUEGO': 'Firearm',
    'INMOLACION': 'Self-Immolation',
    'OTROS': 'Other',
  } as Record<string, string>,

  riskLevels: {
    'Alto': 'High',
    'Moderado': 'Moderate',
    'Bajo': 'Low',
    'Específico': 'Specific',
  } as Record<string, string>,

  fields: {
    edad: 'Patient Age',
    sexo: 'Sex',
    estrato: 'Socioeconomic Stratum',
    gestante: 'Pregnant',
    estadoCivil: 'Marital Status',
    escolaridad: 'Educational Level',
    conflictoPareja: 'Conflict with Partner or Ex-Partner',
    problemasFamiliares: 'Family Problems',
    problemasLaborales: 'Work-Related Problems',
    problemasJuridicos: 'Legal Problems',
    problemasEconomicos: 'Financial Problems',
    muerteFamiliar: 'Death of a Family Member',
    antecedenteViolencia: 'History of Violence or Abuse',
    trastornoDepresivo: 'Depressive Disorder',
    trastornoBipolar: 'Bipolar Disorder',
    trastornoPersonalidad: 'Personality Disorder',
    esquizofrenia: 'Schizophrenia',
    ideacionSuicida: 'Persistent Suicidal Ideation',
    antecedentesFamiliares: 'Family History of Suicidal Behavior',
    consumoSPA: 'Psychoactive Substance Use',
    enfermedadCronica: 'Painful or Disabling Chronic Illness',
    metodoSuicidio: 'Suicide Method',
    intentosPrevios: 'Number of Previous Attempts',
  } as Record<string, string>,

  shortLabels: {
    edad: 'Age',
    sexo: 'Sex',
    estrato: 'Stratum',
    estadoCivil: 'Marital Status',
    escolaridad: 'Education',
    metodo: 'Method',
    intentosPrevios: 'Previous Attempts',
    trastornoDepresivo: 'Depressive Disorder',
    ideacionSuicida: 'Suicidal Ideation',
    consumoSPA: 'Substance Use',
    problemasFamiliares: 'Family Problems',
    conflictoPareja: 'Partner Conflict',
    antecedenteViolencia: 'History of Violence',
    antecedentesFamiliares: 'Family history',
    problemasLaborales: 'Work problems',
  },

  landing: {
    title: 'Psychiatric Referral Prediction System',
    subtitle: 'Stacking Classifier model with 96% accuracy (F1-Score) for clinical decision support',
    heroText: 'Advanced system using K-Means with 3 optimized clusters to segment risk profiles and provide accurate predictions based on 23 variables from the real dataset.',
    startButton: 'Start Assessment',
    metricAccuracy: 'Model Accuracy',
    metricAccuracySub: '(F1-Score)',
    metricRecall: 'System Recall',
    metricRecallSub: 'Complete detection',
    metricClusters: 'K-Means Clusters',
    metricClustersSub: 'Optimized profiles',
    metricVariables: 'Variables Analyzed',
    metricVariablesSub: 'Complete dataset',
    howItWorks: 'How It Works',
    step1Title: 'Data Collection',
    step1Desc: 'Collection of 23 variables from the real dataset, including demographics, risk factors, and clinical conditions.',
    step2Title: 'AI Analysis',
    step2Desc: 'Processing through a Stacking Classifier trained on real data with optimized K-Means segmentation.',
    step3Title: 'Results',
    step3Desc: 'Referral probability calculated with specific recommendations based on the identified risk profile.',
    riskProfilesTitle: 'K-Means Risk Profiles',
    riskProfilesIntro: 'Our system uses K-Means clustering with 3 optimized clusters, outperforming methodologies such as DBSCAN in interpretability and clinical actionability:',
    cluster1Title: 'Cluster 1: High Risk',
    cluster1Desc: 'Young people with multiple risk factors, high-lethality methods, and low family support.',
    cluster2Title: 'Cluster 2: Moderate Risk',
    cluster2Desc: 'Adults with medical comorbidities and major depression, low-to-medium lethality methods.',
    cluster3Title: 'Cluster 3: Specific Risk',
    cluster3Desc: 'Older adults with social isolation and recent losses, detailed planning.',
  },

  form: {
    step1Title: 'Demographic Information',
    step2Title: 'Social and Relational Factors',
    step3Title: 'Mental Health Conditions',
    step4Title: 'Method and Attempt History',
    step5Title: 'Final Review',
    agePlaceholder: '0-120 years',
    attemptsPlaceholder: '0-20',
    stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
    completed: (pct: number) => `${pct}% completed`,
    backToHome: 'Back to Home',
    previous: 'Previous',
    next: 'Next',
    generate: 'Generate Prediction',
    reviewDemographics: 'Demographics Panel',
    reviewClinical: 'Clinical Conditions Panel',
    reviewRiskFactors: 'Risk Factors Panel',
    modelInfoTitle: '⚠️ Model Information',
    modelInfoText: 'This analysis uses a Stacking Classifier trained on 23 variables from the real dataset, achieving a 96% F1-Score and 100% Recall. The results are a clinical decision-support tool and require professional supervision.',
  },

  results: {
    title: 'Prediction Results',
    export: 'Export',
    share: 'Share',
    probabilityTitle: 'Referral Probability',
    riskLevelLabel: 'Risk Level:',
    recommendationTitle: 'Clinical Recommendation',
    recommendationHigh: 'Immediate psychiatric referral recommended. Consider hospitalization and intensive follow-up.',
    recommendationModerate: 'Psychiatric referral within 24-48 hours. Establish a safety plan and follow-up.',
    recommendationLow: 'Outpatient psychological evaluation recommended. Continuous monitoring of risk factors.',
    modelMetricsTitle: 'Model Metrics',
    modelMetricsText: 'Stacking Classifier trained on a real dataset of 487 cases. It combines multiple algorithms to maximize predictive accuracy.',
    f1Score: 'F1-Score',
    recall: 'Recall',
    riskFactorsTitle: 'Identified Risk Factors',
    noRiskFactors: 'No significant risk factors were identified',
    factorYoungAge: 'Young age (< 25 years)',
    factorPreviousAttempts: 'Previous attempts',
    factorDepressive: 'Depressive disorder present',
    factorSuicidalIdeation: 'Persistent suicidal ideation',
    factorSubstanceUse: 'Substance use',
    factorFamilyHistory: 'Family history',
    factorFamilyProblems: 'Family problems',
    factorPartnerConflict: 'Partner conflict',
    factorViolenceHistory: 'History of violence',
    caseSummaryTitle: 'Case Summary',
    demographics: 'Demographics',
    clinical: 'Clinical',
    riskFactors: 'Risk Factors',
    variablesTitle: 'Model Variables (23 factors)',
    newEvaluation: 'New Assessment',
    viewDashboard: 'View Dashboard',
    disclaimerTitle: '⚠️ Medical Disclaimer',
    disclaimerText: 'This system is a clinical decision-support tool and does NOT replace professional medical judgment. Results must be interpreted by qualified healthcare personnel. Always consider the comprehensive clinical evaluation of the patient and the specific circumstances of the case. In emergency situations, contact emergency mental health services immediately.',
  },

  dashboard: {
    title: 'Analytics Dashboard',
    subtitle: 'Statistics and risk profiles based on K-Means',
    period1m: '1 month',
    period3m: '3 months',
    period6m: '6 months',
    period1y: '1 year',
    regionAll: 'All',
    regionUrban: 'Urban',
    regionRural: 'Rural',
    regionSuburban: 'Suburban',
    totalCases: 'Total Cases',
    totalCasesSub: 'Sum of the 3 clusters',
    avgReferral: 'Average Referral Rate',
    avgReferralSub: 'Average across clusters',
    kmeansClusters: 'K-Means Clusters',
    kmeansClustersSub: 'Optimized profiles',
    aiAccuracy: 'AI Accuracy',
    aiAccuracySub: 'Stacking F1-Score',
    tabProfiles: 'Risk Profiles',
    tabTrends: 'Trends',
    tabDemographics: 'Demographics',
    tabGeography: 'Geography',
    clusterLabel: 'Cluster',
    riskLabel: 'Risk',
    casesLabel: 'Cases',
    avgAge: 'Average age',
    referralRate: 'Referral rate',
    avgStay: 'Days of stay',
    characteristics: 'Characteristics:',
    cluster1Title: 'Young People with Multiple Risk Factors',
    cluster1Chars: [
      'Alcohol/drug use',
      'Frequent unemployment',
      'High-lethality methods',
      'Multiple previous attempts',
      'Low family support',
      'Legal problems',
    ],
    cluster2Title: 'Adults with Medical Comorbidities',
    cluster2Chars: [
      'Chronic illnesses',
      'Major depression',
      'Persistent chronic pain',
      'Functional limitations',
      'Low-to-medium lethality methods',
      'Moderate social isolation',
    ],
    cluster3Title: 'Older Adults with Social Isolation',
    cluster3Chars: [
      'Significant recent losses',
      'Severe social isolation',
      'Early cognitive decline',
      'Highly lethal methods',
      'Detailed planning',
      'Loss of autonomy',
    ],
    trendsChartTitle: 'Cases vs Referrals Over Time (6 months)',
    trendsChartPlaceholder: 'Time trends chart',
    trendsChartNote: 'Rising trend in early detection (+12% over the last 3 months)',
    triggersTitle: 'Most Common Triggering Factors',
    triggerFamily: 'Family problems',
    triggerDepressive: 'Depressive disorder',
    triggerSubstance: 'Psychoactive substance use',
    triggerEconomic: 'Financial problems',
    ageDistTitle: 'Age Distribution',
    ageDistPlaceholder: 'Age group pie chart',
    ageGroup1: '18-25 years: 40.5%',
    ageGroup2: '26-45 years: 33.7%',
    ageGroup3: '45+ years: 25.8%',
    methodsByGenderTitle: 'Methods by Gender',
    femaleLabel: 'Female (62%)',
    maleLabel: 'Male (38%)',
    methodPoisoning: 'Poisoning',
    methodSharpWeapon: 'Sharp weapon',
    methodOther: 'Other methods',
    methodHanging: 'Hanging',
    methodFirearm: 'Firearm',
    methodJumping: 'Jumping from a height',
    casesByRegionTitle: 'Cases by Region',
    regionCentral: 'Central Region',
    regionNorth: 'Northern Region',
    regionSouth: 'Southern Region',
    regionEast: 'Eastern Region',
    regionWest: 'Western Region',
    geoCorrelationTitle: 'Location-Risk Correlation',
    geoCorrelationPlaceholder: 'Geographic correlation map',
    geoCorrelationNote: 'Higher concentration of cases in central urban areas',
  },

  legal: {
    title: 'Legal Information and Support',
    subtitle: 'Terms of use, privacy policies, and important information about the system',
    sectionDisclaimer: 'Medical Disclaimer',
    sectionTerms: 'Terms of Use',
    sectionPrivacy: 'Privacy Policy',
    sectionModel: 'Model Information',
    sectionContact: 'Contact and Support',

    importantTitle: '⚠️ IMPORTANT - READ BEFORE USE',
    importantText: 'This system is ONLY a clinical decision-support tool. It does NOT constitute a medical diagnosis, nor does it replace professional evaluation.',
    limitationsTitle: 'System Limitations',
    limitation1: 'Results are probabilistic and must be interpreted by qualified medical personnel',
    limitation2: 'It does not consider specific clinical factors not included in the model’s 23 variables',
    limitation3: 'It requires supervision and validation by mental health professionals',
    limitation4: 'It must not be used as the sole criterion for making clinical decisions',
    responsibilityTitle: 'Professional Responsibility',
    responsibilityText: 'The treating physician retains full responsibility for the diagnosis, treatment, and follow-up of the patient. This system provides supplementary information that must be evaluated within the comprehensive clinical context of the case.',
    emergencyTitle: 'Emergency Situations',
    emergencyText: 'In cases of imminent risk or psychiatric emergencies, contact immediately:',
    emergencyLine1: '• Crisis Line: 123 (24 hours)',
    emergencyLine2: '• The emergency department of the nearest hospital',
    emergencyLine3: '• Do not rely solely on this system for urgent decisions',

    conditionsTitle: 'Conditions of Use',
    condition1: 'This system is intended exclusively for healthcare professionals',
    condition2: 'A valid medical license is required for clinical use of the results',
    condition3: 'Use for non-medical or research purposes without authorization is prohibited',
    condition4: 'Users are responsible for maintaining the confidentiality of patient data',
    condition5: 'All local and international health regulations must be complied with',
    liabilityTitle: 'Limitations of Liability',
    liabilityText: 'The system is provided "as is" without warranties of any kind. We are not liable for clinical decisions made based solely on the system’s results.',
    appropriateUseTitle: 'Appropriate Use',
    appropriateUse1: 'Use it as a supplementary decision-support tool',
    appropriateUse2: 'Always combine it with a comprehensive clinical evaluation',
    appropriateUse3: 'Document the use of the system in the medical record',
    appropriateUse4: 'Keep records of the assessments performed',
    updatesTitle: 'Updates and Modifications',
    updatesText: 'We reserve the right to update these terms and the system’s functionality. Users will be notified of significant changes.',

    dataHandlingTitle: 'Patient Data Handling',
    privacyCommitmentLabel: 'Privacy Commitment:',
    privacyCommitmentText: ' All entered data is processed locally and is not stored on external servers without explicit consent.',
    dataCollectionTitle: 'Information Collection',
    dataCollection1: 'We only collect the 23 variables required for the predictive model',
    dataCollection2: 'We do not store personally identifiable information without authorization',
    dataCollection3: 'Data is processed anonymously and in aggregate form for statistics',
    dataCollection4: 'We comply with HIPAA standards and local data protection regulations',
    userRightsTitle: 'User Rights',
    userRight1: 'The right to know what data is processed',
    userRight2: 'The right to request deletion of stored data',
    userRight3: 'The right to rectification of incorrect information',
    userRight4: 'The right to data portability',
    dataSecurityTitle: 'Data Security',
    dataSecurityIntro: 'We implement technical and organizational measures to protect information:',
    security1: 'Data encryption in transit and at rest',
    security2: 'Controlled access and user authentication',
    security3: 'Regular security audits',
    security4: 'Secure data backup and recovery',
    sharingTitle: 'Information Sharing',
    sharingText: 'We do not share patients’ personal data with third parties without explicit consent, except when required by law or for medical research purposes approved by ethics committees.',

    methodologyTitle: 'Stacking Classifier Methodology',
    advancedTechniqueLabel: 'Advanced Technique:',
    advancedTechniqueText: ' It combines multiple machine learning algorithms to maximize predictive accuracy and minimize classification errors.',
    datasetTitle: 'Dataset and Variables',
    trainingDataTitle: 'Training Data',
    trainingData1: '• 487 validated real cases',
    trainingData2: '• 3 optimized K-Means clusters',
    trainingData3: '• 10-fold cross-validation',
    trainingData4: '• Class balancing applied',
    modelVariablesTitle: 'Model Variables',
    modelVariables1: '• 6 demographic variables',
    modelVariables2: '• 7 social/relational factors',
    modelVariables3: '• 8 mental health conditions',
    modelVariables4: '• 2 method/history variables',
    performanceTitle: 'Performance Metrics',
    precisionLabel: 'Precision',
    modelLimitationsTitle: 'Model Limitations',
    modelLimitation1: 'Trained on a specific population (may require calibration for other populations)',
    modelLimitation2: 'It does not include neuroimaging variables or biomarkers',
    modelLimitation3: 'It requires periodic updating with new data',
    modelLimitation4: 'It is sensitive to the quality and completeness of input data',
    clinicalValidationTitle: 'Clinical Validation',
    clinicalValidationText: 'The model has been validated in retrospective studies and requires continuous prospective validation. Regular monitoring of performance in real clinical conditions is recommended.',

    contactInfoTitle: 'Contact Information',
    techSupportTitle: 'Technical Support',
    emailLabel: 'Email:',
    phoneLabel: 'Phone:',
    scheduleLabel: 'Hours:',
    responseLabel: 'Response:',
    techSchedule: 'Monday to Friday, 8:00 AM - 6:00 PM',
    techResponse: '24-48 hours',
    clinicalInquiriesTitle: 'Clinical Inquiries',
    clinicalSchedule: '24/7 for emergencies',
    clinicalResponse: 'Immediate for urgent matters',
    reportProblemsTitle: 'Report Problems',
    reportProblemsIntro: 'To report technical problems or system errors:',
    report1: 'Describe the problem in detail',
    report2: 'Include steps to reproduce the error',
    report3: 'Attach screenshots if possible',
    report4: 'Provide browser/device information',
    trainingTitle: 'Education and Training',
    trainingText: 'We offer training sessions for medical teams on the appropriate use of the system and the interpretation of results.',
    training1: 'In-person and virtual workshops',
    training2: 'Downloadable training materials',
    training3: 'Certification in system use',
    training4: 'Implementation consulting',
    researchTitle: 'Research and Collaborations',
    researchIntro: 'For research proposals or academic collaborations:',
    researchNote: 'We are interested in collaborations to improve the model and expand its application to different populations.',
    systemUpdatesTitle: 'System Updates',
    systemUpdatesText: 'To receive notifications about updates, new features, and research newsletters, subscribe to our mailing list at:',

    footerTitle: 'Psychiatric Referral Prediction System',
    footerModel: 'Stacking Classifier Model - F1-Score 96% - Version 1.0',
    footerCopyright: '© 2025 - All rights reserved - For use by healthcare professionals only',
  },
};

const translations: Record<Lang, typeof es> = { es, en };

export type Translations = typeof es;

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
  /** Translates a stored enum value (e.g. "FEMENINO") to its visible label. */
  tv: (value: string) => string;
}

const LangContext = createContext<LangContextType | null>(null);

const STORAGE_KEY = 'wt-lang';

export const LangProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    const initial: Lang = saved === 'en' || saved === 'es' ? saved : 'es';
    document.documentElement.lang = initial;
    document.title = translations[initial].meta.title;
    return initial;
  });

  const setLang = (l: Lang) => {
    localStorage.setItem(STORAGE_KEY, l);
    document.documentElement.lang = l;
    document.title = translations[l].meta.title;
    setLangState(l);
  };

  const t = translations[lang];
  const tv = (value: string) => t.values[value] ?? value;

  return (
    <LangContext.Provider value={{ lang, setLang, t, tv }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
};
